/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class DialogClient extends javax.swing.JDialog {

    /**
     * Creates new form DialogClient
     * @param parent
     * @param modal
     */
    public DialogClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        titolDialog = new javax.swing.JTextPane();
        btnPremium = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNom = new javax.swing.JTextPane();
        inpNom = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCorreu = new javax.swing.JTextPane();
        inpCorreu = new javax.swing.JTextField();
        txtAdreca = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        inpAdreca = new javax.swing.JTextField();
        btnAfegirClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titolDialog.setEditable(false);
        titolDialog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titolDialog.setText("Introdueix les dades del client");
        titolDialog.setToolTipText("");
        jScrollPane1.setViewportView(titolDialog);

        btnPremium.setText("Premium");
        btnPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremiumActionPerformed(evt);
            }
        });

        txtNom.setEditable(false);
        txtNom.setText("Nom:");
        jScrollPane2.setViewportView(txtNom);

        inpNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomActionPerformed(evt);
            }
        });

        jScrollPane3.setToolTipText("");

        txtCorreu.setEditable(false);
        txtCorreu.setText("Correu electrònic:");
        jScrollPane3.setViewportView(txtCorreu);

        inpCorreu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCorreuActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setText("Adreça:");
        txtAdreca.setViewportView(jTextPane1);

        btnAfegirClient.setBackground(new java.awt.Color(0, 0, 0));
        btnAfegirClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnAfegirClient.setForeground(new java.awt.Color(0, 255, 255));
        btnAfegirClient.setText("Afegir Client");
        btnAfegirClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAfegirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                    .addComponent(txtAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpAdreca)
                                    .addComponent(inpCorreu)
                                    .addComponent(inpNom))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 438, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(468, 468, 468))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(433, 433, 433))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(inpCorreu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(inpNom))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdreca, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(inpAdreca))
                .addGap(54, 54, 54)
                .addComponent(btnPremium)
                .addGap(18, 18, 18)
                .addComponent(btnAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPremiumActionPerformed

    private void inpNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomActionPerformed

    private void inpCorreuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCorreuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCorreuActionPerformed

    private void btnAfegirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirClientActionPerformed
        try {
            // TODO add your handling code here:
            boolean premium = btnPremium.isSelected();
            String correu = inpCorreu.getText();
            String nom = inpNom.getText();
            String adreca = inpAdreca.getText();
            
            if(correu.length() == 0 || nom.length() == 0 || adreca.length()==0)
                throw new RuntimeException();
            
            AppMercatUB.controlador.afegirClient(correu, nom, adreca, premium);
            JOptionPane.showMessageDialog(null, "Client afegit amb èxit!");
        }catch (MercatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (RuntimeException exc) {
            JOptionPane.showMessageDialog(null, "Has deixat algún camp buit.");
        }finally{
            this.dispose();
        }
    }//GEN-LAST:event_btnAfegirClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogClient dialog = new DialogClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirClient;
    private javax.swing.JRadioButton btnPremium;
    private javax.swing.JTextField inpAdreca;
    private javax.swing.JTextField inpCorreu;
    private javax.swing.JTextField inpNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane titolDialog;
    private javax.swing.JScrollPane txtAdreca;
    private javax.swing.JTextPane txtCorreu;
    private javax.swing.JTextPane txtNom;
    // End of variables declaration//GEN-END:variables
}
