/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author USUARIO
 */
public class FrmGestioComandes extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestioComandes
     */
    public FrmGestioComandes() {
        initComponents();
        btnEsborraComanda.setEnabled(false);
        panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVisualitzaComandes = new javax.swing.JButton();
        btnAfegeixComanda = new javax.swing.JButton();
        btnUrgents = new javax.swing.JCheckBox();
        btnEsborraComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaComandes = new javax.swing.JList<>();
        panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        llistaClients = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        llistaArticles = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextPane();
        inpQuantitat = new javax.swing.JTextField();
        btnUrgent = new javax.swing.JRadioButton();
        afegirComanda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnVisualitzaComandes.setText("Visualitza Comandes");
        btnVisualitzaComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzaComandesActionPerformed(evt);
            }
        });

        btnAfegeixComanda.setText("Afegeix Comanda");
        btnAfegeixComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegeixComandaActionPerformed(evt);
            }
        });

        btnUrgents.setText("Urgents");
        btnUrgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrgentsActionPerformed(evt);
            }
        });

        btnEsborraComanda.setText("Esborra Comanda");
        btnEsborraComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsborraComandaActionPerformed(evt);
            }
        });

        llistaComandes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                llistaComandesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(llistaComandes);

        panel.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane2.setViewportView(llistaClients);

        jScrollPane3.setViewportView(llistaArticles);

        text1.setEditable(false);
        text1.setText("Quantitat:");
        jScrollPane4.setViewportView(text1);

        btnUrgent.setText("Urgent");

        afegirComanda.setBackground(new java.awt.Color(51, 51, 51));
        afegirComanda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        afegirComanda.setForeground(new java.awt.Color(0, 204, 255));
        afegirComanda.setText("Afegeix Comanda");
        afegirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afegirComanda))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(btnUrgent)
                        .addGap(444, 444, 444))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnUrgent)
                .addGap(18, 18, 18)
                .addComponent(afegirComanda)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEsborraComanda)
                    .addComponent(btnAfegeixComanda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisualitzaComandes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUrgents)))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualitzaComandes)
                    .addComponent(btnUrgents))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEsborraComanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAfegeixComanda)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualitzaComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzaComandesActionPerformed
        // TODO add your handling code here:
        showComandes(btnUrgents.isSelected());
    }//GEN-LAST:event_btnVisualitzaComandesActionPerformed

    private void btnEsborraComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsborraComandaActionPerformed
        // TODO add your handling code here:

        for (int i : llistaComandes.getSelectedIndices()) {
            try {
                AppMercatUB.controlador.esborrarComanda(i);
            } catch (MercatException ex) {
                Logger.getLogger(FrmGestioComandes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        showComandes(btnUrgents.isSelected());
    }//GEN-LAST:event_btnEsborraComandaActionPerformed

    private void llistaComandesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_llistaComandesValueChanged
        // TODO add your handling code here:

        // Solo se podrá borrar cuando el botón de urgente esté desactivado
        btnEsborraComanda.setEnabled(!llistaComandes.isSelectionEmpty() && !btnUrgents.isSelected());
    }//GEN-LAST:event_llistaComandesValueChanged

    private void btnAfegeixComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegeixComandaActionPerformed
        // TODO add your handling code here:
        panel.setVisible(true);
        showArticles();
        showClients();
    }//GEN-LAST:event_btnAfegeixComandaActionPerformed

    private void afegirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirComandaActionPerformed
        try {
            // TODO add your handling code here:
            int articlePos = llistaArticles.getSelectedIndex();
            int clientPos = llistaClients.getSelectedIndex();
            afegirComanda.setEnabled(true);
            int quantitat = Integer.parseInt(inpQuantitat.getText());
            boolean esUrgent = btnUrgent.isSelected();

            AppMercatUB.controlador.afegirComanda(articlePos, clientPos, quantitat, esUrgent);
        } catch (MercatException ex) {
            Logger.getLogger(FrmGestioComandes.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            panel.setVisible(false);
        }
    }//GEN-LAST:event_afegirComandaActionPerformed

    private void btnUrgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrgentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUrgentsActionPerformed

    void showArticles() {
        DefaultListModel model = new DefaultListModel();
        model.clear();

        List<String> llista = AppMercatUB.controlador.recuperaArticles();

        for (int i = 0; i < llista.size(); i++) {
            model.addElement(llista.get(i));
        }

        llistaArticles.setModel(model);
    }

    void showClients() {
        DefaultListModel model = new DefaultListModel();
        model.clear();

        List<String> llista = AppMercatUB.controlador.recuperaClients();

        for (int i = 0; i < llista.size(); i++) {
            model.addElement(llista.get(i));
        }

        llistaClients.setModel(model);
    }

    void showComandes(boolean urgent) {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        List<String> llista;

        if (!urgent) {
            llista = AppMercatUB.controlador.recuperaComandes();
        } else {
            llista = AppMercatUB.controlador.recuperaComandesUrgents();
        }

        for (int i = 0; i < llista.size(); i++) {
            model.addElement(llista.get(i));
        }

        llistaComandes.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestioComandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestioComandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestioComandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestioComandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestioComandes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirComanda;
    private javax.swing.JButton btnAfegeixComanda;
    private javax.swing.JButton btnEsborraComanda;
    private javax.swing.JRadioButton btnUrgent;
    private javax.swing.JCheckBox btnUrgents;
    private javax.swing.JButton btnVisualitzaComandes;
    private javax.swing.JTextField inpQuantitat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> llistaArticles;
    private javax.swing.JList<String> llistaClients;
    private javax.swing.JList<String> llistaComandes;
    private javax.swing.JPanel panel;
    private javax.swing.JTextPane text1;
    // End of variables declaration//GEN-END:variables
}
