/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author USUARIO
 */
public class FrmGestioArticles extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestioArticles
     */
    public FrmGestioArticles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVisualitzaArticles = new javax.swing.JButton();
        btnAfegirArticle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaArticles = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Articles");

        btnVisualitzaArticles.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualitzaArticles.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnVisualitzaArticles.setForeground(new java.awt.Color(0, 255, 255));
        btnVisualitzaArticles.setText("Visualitzar Articles");
        btnVisualitzaArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzaArticlesActionPerformed(evt);
            }
        });

        btnAfegirArticle.setBackground(new java.awt.Color(0, 0, 0));
        btnAfegirArticle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAfegirArticle.setForeground(new java.awt.Color(102, 255, 102));
        btnAfegirArticle.setText("Afegir Article");
        btnAfegirArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirArticleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(llistaArticles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAfegirArticle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisualitzaArticles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnVisualitzaArticles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAfegirArticle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirArticleActionPerformed
        // TODO add your handling code here:
        DialogArticle dialog = new DialogArticle(this,true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAfegirArticleActionPerformed

    private void btnVisualitzaArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzaArticlesActionPerformed
        // TODO add your handling code here:
        showArticles();
        
    }//GEN-LAST:event_btnVisualitzaArticlesActionPerformed

    void showArticles() {
        DefaultListModel model = new DefaultListModel();
        model.clear();

        List<String> llista = AppMercatUB.controlador.recuperaArticles();

        for (int i = 0; i < llista.size(); i++)
            model.addElement(llista.get(i));
        

        llistaArticles.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestioArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestioArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestioArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestioArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestioArticles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirArticle;
    private javax.swing.JButton btnVisualitzaArticles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> llistaArticles;
    // End of variables declaration//GEN-END:variables
}
